language: node_js
node_js:
  - "8"
cache: yarn
script:
  - npm test
  - npm run build
  - echo $ADMIN_TOKEN > ADMIN_TOKEN
deploy:
  provider: heroku
  app: cloudboard-app
  skip_cleanup: true
  api_key:
    secure: $HEROKU_API_KEY
